use_frameworks!
target 'OrbitaFramework_Example' do
  pod 'OrbitaFramework', :path => '../'
  pod 'Efficio', :path => '../../Efficio'
  # pod 'Efficio', :git => 'https://github.com/jakecasino/Efficio', :branch => 'master'
  
end
